---
- label: Getting Support
  href: /support
- label: FAQ
  links:
    - href: /support/faq/overview.mdx
      label: "Overview"
    - href: /support/faq/thoth_yaml.mdx
      label: "Default .thoth.yaml"
- label: "Track your issue"
  href: /support/issue_tracker.mdx